Repository openshift/node_exporter, pull requests merged in 2019-11, with the labels that each got.

#36 text_collectors: Add a virtualization metric series from virt-what
  Dockerfile.ocp
  text_collectors/virt.sh
Labels: approved, lgtm, size/M

#37 text_collectors: Fix virt.sh to include help text
  text_collectors/virt.sh
Labels: approved, lgtm, size/XS

#41 Bug 1773243: If no virt platform is detected, set type to 'none'
  text_collectors/virt.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#42 Bug 1775454: virtwhat multiple platform
  text_collectors/virt.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#40 Bug 1773246: Add a virtualization metric series from virt-what
  Dockerfile.ocp
  text_collectors/virt.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
