Repository openshift/node_exporter, pull requests merged in 2019-10, with the labels that each got.

#32 Merge v0.18.1 release
  .circleci/config.yml
  CHANGELOG.md
  VERSION
  collector/fixtures/e2e-64k-page-output.txt
  collector/fixtures/e2e-output.txt
  collector/fixtures/proc/10/mountstats
  collector/memory_bsd.go
  collector/mountstats_linux.go
  go.mod
  go.sum
  text_collector_examples/md_info_detail.sh
  vendor/github.com/prometheus/procfs/MAINTAINERS.md
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/fs.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_dev.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/nfs/parse.go
  vendor/github.com/prometheus/procfs/proc_ns.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/sysfs/clocksource.go
  vendor/github.com/prometheus/procfs/ttar
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#33 add node_cpu_info metric
  CHANGELOG.md
  collector/cpu_linux.go
  collector/fixtures/e2e-64k-page-output.txt
  collector/fixtures/e2e-output.txt
  collector/fixtures/proc/cpuinfo
  end-to-end-test.sh
  go.mod
  go.sum
  vendor/github.com/prometheus/procfs/cpuinfo.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#34 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#35 Use Go 1.12 instead of 1.11
  Dockerfile.ocp
Labels: approved, lgtm, size/XS
