Repository openshift/node_exporter, pull requests merged in 2020-01, with the labels that each got.

#47 Dockerfile.ocp: upgrade Go to 1.13
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#48 Bug 1789083: Not reporting 'none' when no platforms located
  text_collectors/virt.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#52 Disable cpu info metric on non x86 arches
  collector/cpu_linux.go
Labels: approved, lgtm, size/XS

#51 text_collectors: Detect AWS and GCP virt platform type
  text_collectors/virt.sh
Labels: approved, lgtm, size/S
